name = "reyliar-discord-user"
main = "workers/discord-user.js"
compatibility_date = "2026-06-06"

routes = [
  { pattern = "reyliar.xyz/api/*", zone_name = "reyliar.xyz" }
]

[[kv_namespaces]]
binding = "VIEW_COUNTER"
id = "3955803c2fc542049cdc3145c8c447bf"

[[durable_objects.bindings]]
name = "DISCORD_PROFILE_STATE"
class_name = "DiscordProfileState"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DiscordProfileState"]
